#!/bin/bash

# BACKGROUND
nitrogen --restore &

# COMPTON
compton &

# REDSHIFT
redshift -t 6500:3100 &

# KEYBOARD SPEED
xset r rate 200 60

# KEYBOARD MAPPINGS
setxkbmap -option caps:escape
xmodmap -e "keycode 134 = Escape"

# XRANDR
xrandr --output DP-0 --auto --primary \
       --output HDMI-0 --auto --left-of DP-0 \
       --output DP-2 --auto --right-of DP-0

exec qtile start
