#!/bin/bash

# BACKGROUND
nitrogen --restore &

# COMPTON
# compton &

# KEYBOARD SPEED
xset r rate 200 60

# KEYBOARD MAPPINGS
setxkbmap -option caps:escape

# TOUCHPAD CLICK
synclient tapbutton1=1
synclient VertScrollDelta=-100
synclient PalmDetect=1

# XRANDR
# xrandr --output DP-0 --auto --primary \
#        --output HDMI-0 --auto --left-of DP-0 \
#        --output DP-2 --auto --right-of DP-0

exec /home/unicorn/.local/bin/qtile start
